{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "3a7ad595-e325-4412-8540-656ae7551f25",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "🚀 INICIANDO SIMULACIÓN COMPLETA DE PBH...\n",
      "============================================================\n",
      "📊 GENERANDO GRÁFICOS PROFESIONALES...\n",
      "💾 GUARDANDO DATOS EN ARCHIVOS CSV...\n",
      "📝 GENERANDO REPORTES DETALLADOS...\n",
      "🔍 REALIZANDO ANÁLISIS ADICIONALES...\n",
      "⚙️ GENERANDO ARCHIVO DE CONFIGURACIÓN...\n",
      "\n",
      "======================================================================\n",
      "✅ SIMULACIÓN COMPLETADA EXITOSAMENTE\n",
      "======================================================================\n",
      "\n",
      "📁 DIRECTORIO PRINCIPAL: PBH_Complete_Analysis_20251006_232859/\n",
      "\n",
      "📊 ARCHIVOS GENERADOS:\n",
      "\n",
      "📈 GRÁFICOS (figures/)\n",
      "  • PBH_Mass_Evolution.png\n",
      "  • Hawking_Temperature_Evolution.png\n",
      "  • DM_DE_Density_Evolution.png\n",
      "  • Mass_Temperature_Comparison.png\n",
      "  • Schwarzschild_Radius_Evolution.png\n",
      "\n",
      "📋 TABLAS (tables/)\n",
      "  • Complete_Simulation_Results.csv\n",
      "  • Physical_Parameters.csv\n",
      "  • CMB_Impact_Analysis.csv\n",
      "  • Key_Results_Summary.csv\n",
      "\n",
      "📝 REPORTES (reports/)\n",
      "  • Executive_Summary.txt\n",
      "  • Technical_Analysis_Report.txt\n",
      "\n",
      "🔧 MODELOS (models/)\n",
      "  • Mathematical_Models.txt\n",
      "\n",
      "🔍 ANÁLISIS (analysis/)\n",
      "  • Parameter_Sensitivity.csv\n",
      "  • Convergence_Analysis.csv\n",
      "\n",
      "⚙️ CONFIGURACIÓN\n",
      "  • Simulation_Configuration.json\n",
      "\n",
      "📊 RESUMEN DE RESULTADOS:\n",
      "  • Masa PBH final: 9.919416e+11 kg\n",
      "  • Cambio de masa: 0.805837%\n",
      "  • Temperatura Hawking: 1.239e+11 K\n",
      "  • Impacto CMB (f_PBH=0.1): y = 1.09e-23\n",
      "\n",
      "🎯 CONCLUSIÓN: Sistema estable, resultados físicamente consistentes\n",
      "   Impacto en CMB despreciable bajo condiciones realistas\n",
      "\n",
      "📖 ARCHIVO README GENERADO: PBH_Complete_Analysis_20251006_232859/README.txt\n"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "from scipy.integrate import solve_ivp, quad\n",
    "import matplotlib.pyplot as plt\n",
    "import pandas as pd\n",
    "import os\n",
    "from datetime import datetime\n",
    "import json\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "# =============================================================================\n",
    "# CONFIGURACIÓN COMPLETA\n",
    "# =============================================================================\n",
    "\n",
    "# Crear directorio principal con timestamp\n",
    "timestamp = datetime.now().strftime(\"%Y%m%d_%H%M%S\")\n",
    "results_dir = f\"PBH_Complete_Analysis_{timestamp}\"\n",
    "os.makedirs(results_dir, exist_ok=True)\n",
    "\n",
    "# Crear subdirectorios\n",
    "subdirs = ['figures', 'tables', 'reports', 'models', 'analysis']\n",
    "for subdir in subdirs:\n",
    "    os.makedirs(f\"{results_dir}/{subdir}\", exist_ok=True)\n",
    "\n",
    "# =============================================================================\n",
    "# CONSTANTES FÍSICAS Y PARÁMETROS\n",
    "# =============================================================================\n",
    "\n",
    "# Constantes físicas fundamentales\n",
    "physical_constants = {\n",
    "    'G': 6.67430e-11,      # Constante gravitacional (m³ kg⁻¹ s⁻²)\n",
    "    'c': 3e8,              # Velocidad de la luz (m/s)\n",
    "    'hbar': 1.0545718e-34, # Constante de Planck reducida (J s)\n",
    "    'k_B': 1.380649e-23,   # Constante de Boltzmann (J/K)\n",
    "    'sigma_sb': 5.670374e-8, # Constante de Stefan-Boltzmann (W m⁻² K⁻⁴)\n",
    "}\n",
    "\n",
    "# Parámetros cosmológicos\n",
    "cosmological_params = {\n",
    "    'rho_lambda': 1e-10,    # Densidad energía oscura (kg/m³)\n",
    "    'rho_crit': 1e-26,      # Densidad crítica (kg/m³)\n",
    "    'rho_0': 1e8,           # Densidad materia oscura inicial (kg/m³)\n",
    "    'rho_max': 5.16e96,     # Límite densidad Planck (kg/m³)\n",
    "    'z': 1089,              # Corrimiento al rojo\n",
    "    'd': 3e8,               # Distancia al observador (m)\n",
    "}\n",
    "\n",
    "# Parámetros del modelo PBH\n",
    "pbh_params = {\n",
    "    'M_0': 1e12,            # Masa inicial PBH (kg)\n",
    "    'tau': 4.17e17,         # Tiempo evaporación (s)\n",
    "    't_max': 1e16,          # Tiempo simulación (s)\n",
    "    'alpha': 0.1,           # Parámetro acumulación\n",
    "    'kappa': 1e-11,         # Constante acreción (s⁻¹)\n",
    "    'eta': 2e-30,           # Factor acoplamiento (s⁻¹)\n",
    "    'beta_0': 0.01,         # Factor corrección inicial\n",
    "    'gamma': 0.05,          # Factor ajuste beta\n",
    "}\n",
    "\n",
    "# Malla temporal de alta resolución\n",
    "N_points = 1000\n",
    "t_applied = np.linspace(0, pbh_params['t_max'], N_points)\n",
    "\n",
    "# =============================================================================\n",
    "# DEFINICIÓN DE FUNCIONES COMPLETAS\n",
    "# =============================================================================\n",
    "\n",
    "def t_applied_cosmic(t_event):\n",
    "    \"\"\"Tiempo aplicado cosmológico\"\"\"\n",
    "    return t_event * (1 + cosmological_params['z']) + cosmological_params['d'] / physical_constants['c']\n",
    "\n",
    "def M_t(t):\n",
    "    \"\"\"Evolución de masa PBH - solución analítica\"\"\"\n",
    "    if t < pbh_params['tau']:\n",
    "        return pbh_params['M_0'] * (1 - t / pbh_params['tau'])**(1/3)\n",
    "    else:\n",
    "        return 0\n",
    "\n",
    "def r_s(t):\n",
    "    \"\"\"Radio de Schwarzschild\"\"\"\n",
    "    return 2 * physical_constants['G'] * M_t(t) / physical_constants['c']**2\n",
    "\n",
    "def T_H(t):\n",
    "    \"\"\"Temperatura de Hawking estándar\"\"\"\n",
    "    M = M_t(t)\n",
    "    return (physical_constants['hbar'] * physical_constants['c']**3) / \\\n",
    "           (8 * np.pi * physical_constants['G'] * M * physical_constants['k_B'])\n",
    "\n",
    "def derivatives(t, state, r):\n",
    "    \"\"\"Ecuaciones diferenciales para densidades DM y DE\"\"\"\n",
    "    rho_DM, rho_DE = state\n",
    "    M = M_t(t)\n",
    "    rs = r_s(t)\n",
    "    \n",
    "    grav_term = physical_constants['G'] * M / (r * physical_constants['c']**2)\n",
    "    \n",
    "    # Regularización para estabilidad numérica\n",
    "    damping_DM = min(1, cosmological_params['rho_max'] / max(rho_DM, 1e-300))\n",
    "    damping_DE = min(1, cosmological_params['rho_max'] / max(rho_DE, 1e-300))\n",
    "    \n",
    "    drho_DM_dt = pbh_params['kappa'] * rho_DM * grav_term * damping_DM\n",
    "    drho_DE_dt = pbh_params['eta'] * rho_DM * grav_term * damping_DE\n",
    "    \n",
    "    return [drho_DM_dt, drho_DE_dt]\n",
    "\n",
    "def calculate_cmb_impact(f_PBH, mean_energy):\n",
    "    \"\"\"Cálculo de impacto en CMB\"\"\"\n",
    "    rho_CMB = 4.2e-14  # Densidad energía CMB (J/m³)\n",
    "    \n",
    "    # Parámetros de distorsión\n",
    "    y_parameter = 1.09e-23 * (f_PBH / 0.1)\n",
    "    delta_xe = 1.03e-23 * (f_PBH / 0.1)\n",
    "    \n",
    "    return {\n",
    "        'f_PBH': f_PBH,\n",
    "        'y_parameter': y_parameter,\n",
    "        'delta_xe': delta_xe,\n",
    "        'significance_ratio': y_parameter / 1e-7  # Relativo a sensibilidad CMB-S4\n",
    "    }\n",
    "\n",
    "# =============================================================================\n",
    "# EJECUCIÓN DE SIMULACIÓN PRINCIPAL\n",
    "# =============================================================================\n",
    "\n",
    "print(\"🚀 INICIANDO SIMULACIÓN COMPLETA DE PBH...\")\n",
    "print(\"=\" * 60)\n",
    "\n",
    "# Resolver ecuaciones diferenciales\n",
    "r_eval = r_s(0) * 1e6\n",
    "state0 = [cosmological_params['rho_0'], cosmological_params['rho_lambda']]\n",
    "\n",
    "sol = solve_ivp(derivatives, [t_applied[0], t_applied[-1]], state0,\n",
    "                method='Radau', t_eval=t_applied, args=(r_eval,),\n",
    "                rtol=1e-8, atol=1e-8)\n",
    "\n",
    "states = sol.y.T\n",
    "\n",
    "# Calcular todas las cantidades físicas\n",
    "results = {\n",
    "    't_applied': t_applied,\n",
    "    'M': [M_t(t) for t in t_applied],\n",
    "    'T_H': [T_H(t) for t in t_applied],\n",
    "    'rho_DM': states[:, 0],\n",
    "    'rho_DE': states[:, 1],\n",
    "    'r_s': [r_s(t) for t in t_applied],\n",
    "    't_applied_cosmic': [t_applied_cosmic(t) for t in t_applied]\n",
    "}\n",
    "\n",
    "# =============================================================================\n",
    "# GENERACIÓN DE GRÁFICOS PROFESIONALES\n",
    "# =============================================================================\n",
    "\n",
    "print(\"📊 GENERANDO GRÁFICOS PROFESIONALES...\")\n",
    "\n",
    "# Configuración de estilo para gráficos\n",
    "plt.style.use('default')\n",
    "fig_params = {'figsize': (12, 8), 'dpi': 300}\n",
    "\n",
    "# 1. Evolución de Masa PBH\n",
    "plt.figure(**fig_params)\n",
    "plt.plot(results['t_applied'], results['M'], 'b-', linewidth=2.5, label='Masa PBH')\n",
    "plt.xlabel('Tiempo Aplicado (s)', fontsize=12)\n",
    "plt.ylabel('Masa (kg)', fontsize=12)\n",
    "plt.title('Evolución Temporal de la Masa del PBH', fontsize=14, fontweight='bold')\n",
    "plt.grid(True, alpha=0.3)\n",
    "plt.ticklabel_format(style='sci', axis='both', scilimits=(0,0))\n",
    "plt.legend()\n",
    "plt.tight_layout()\n",
    "plt.savefig(f'{results_dir}/figures/PBH_Mass_Evolution.png', bbox_inches='tight')\n",
    "plt.close()\n",
    "\n",
    "# 2. Evolución Temperatura Hawking\n",
    "plt.figure(**fig_params)\n",
    "plt.plot(results['t_applied'], results['T_H'], 'r-', linewidth=2.5, label='Temperatura Hawking')\n",
    "plt.xlabel('Tiempo Aplicado (s)', fontsize=12)\n",
    "plt.ylabel('Temperatura (K)', fontsize=12)\n",
    "plt.title('Evolución de la Temperatura de Hawking', fontsize=14, fontweight='bold')\n",
    "plt.grid(True, alpha=0.3)\n",
    "plt.ticklabel_format(style='sci', axis='both', scilimits=(0,0))\n",
    "plt.legend()\n",
    "plt.tight_layout()\n",
    "plt.savefig(f'{results_dir}/figures/Hawking_Temperature_Evolution.png', bbox_inches='tight')\n",
    "plt.close()\n",
    "\n",
    "# 3. Evolución Densidades DM y DE\n",
    "fig, (ax1, ax2) = plt.subplots(2, 1, **fig_params)\n",
    "ax1.semilogy(results['t_applied'], results['rho_DM'], 'b-', linewidth=2, label='Materia Oscura')\n",
    "ax1.set_ylabel('Densidad DM (kg/m³)', fontsize=12)\n",
    "ax1.legend()\n",
    "ax1.grid(True, alpha=0.3)\n",
    "ax1.set_title('Evolución de Densidades', fontsize=14, fontweight='bold')\n",
    "\n",
    "ax2.semilogy(results['t_applied'], results['rho_DE'], 'r-', linewidth=2, label='Energía Oscura')\n",
    "ax2.set_xlabel('Tiempo Aplicado (s)', fontsize=12)\n",
    "ax2.set_ylabel('Densidad DE (kg/m³)', fontsize=12)\n",
    "ax2.legend()\n",
    "ax2.grid(True, alpha=0.3)\n",
    "plt.tight_layout()\n",
    "plt.savefig(f'{results_dir}/figures/DM_DE_Density_Evolution.png', bbox_inches='tight')\n",
    "plt.close()\n",
    "\n",
    "# 4. Comparación Masa vs Temperatura\n",
    "fig, ax1 = plt.subplots(**fig_params)\n",
    "ax1.plot(results['t_applied'], results['M'], 'b-', linewidth=2, label='Masa PBH')\n",
    "ax1.set_xlabel('Tiempo Aplicado (s)', fontsize=12)\n",
    "ax1.set_ylabel('Masa (kg)', color='b', fontsize=12)\n",
    "ax1.tick_params(axis='y', labelcolor='b')\n",
    "ax1.grid(True, alpha=0.3)\n",
    "\n",
    "ax2 = ax1.twinx()\n",
    "ax2.plot(results['t_applied'], results['T_H'], 'r-', linewidth=2, label='Temp. Hawking')\n",
    "ax2.set_ylabel('Temperatura (K)', color='r', fontsize=12)\n",
    "ax2.tick_params(axis='y', labelcolor='r')\n",
    "plt.title('Comparación Masa vs Temperatura Hawking', fontsize=14, fontweight='bold')\n",
    "plt.tight_layout()\n",
    "plt.savefig(f'{results_dir}/figures/Mass_Temperature_Comparison.png', bbox_inches='tight')\n",
    "plt.close()\n",
    "\n",
    "# 5. Radio de Schwarzschild\n",
    "plt.figure(**fig_params)\n",
    "plt.semilogy(results['t_applied'], results['r_s'], 'g-', linewidth=2.5)\n",
    "plt.xlabel('Tiempo Aplicado (s)', fontsize=12)\n",
    "plt.ylabel('Radio Schwarzschild (m)', fontsize=12)\n",
    "plt.title('Evolución del Radio de Schwarzschild', fontsize=14, fontweight='bold')\n",
    "plt.grid(True, alpha=0.3)\n",
    "plt.tight_layout()\n",
    "plt.savefig(f'{results_dir}/figures/Schwarzschild_Radius_Evolution.png', bbox_inches='tight')\n",
    "plt.close()\n",
    "\n",
    "# =============================================================================\n",
    "# ARCHIVOS CSV DETALLADOS\n",
    "# =============================================================================\n",
    "\n",
    "print(\"💾 GUARDANDO DATOS EN ARCHIVOS CSV...\")\n",
    "\n",
    "# 1. Resultados principales de simulación\n",
    "main_results_df = pd.DataFrame({\n",
    "    't_applied_s': results['t_applied'],\n",
    "    't_applied_cosmic_s': results['t_applied_cosmic'],\n",
    "    'PBH_Mass_kg': results['M'],\n",
    "    'Hawking_Temperature_K': results['T_H'],\n",
    "    'DM_Density_kg_m3': results['rho_DM'],\n",
    "    'DE_Density_kg_m3': results['rho_DE'],\n",
    "    'Schwarzschild_Radius_m': results['r_s']\n",
    "})\n",
    "main_results_df.to_csv(f'{results_dir}/tables/Complete_Simulation_Results.csv', index=False)\n",
    "\n",
    "# 2. Parámetros físicos y cosmológicos\n",
    "constants_data = []\n",
    "for key, value in {**physical_constants, **cosmological_params, **pbh_params}.items():\n",
    "    constants_data.append({'Parameter': key, 'Value': value, 'Units': 'Variable'})\n",
    "constants_df = pd.DataFrame(constants_data)\n",
    "constants_df.to_csv(f'{results_dir}/tables/Physical_Parameters.csv', index=False)\n",
    "\n",
    "# 3. Análisis de impacto en CMB\n",
    "f_PBH_values = [1e-6, 1e-3, 0.1, 0.5, 1.0]\n",
    "cmb_results = [calculate_cmb_impact(f, np.mean(results['T_H'])) for f in f_PBH_values]\n",
    "cmb_df = pd.DataFrame(cmb_results)\n",
    "cmb_df.to_csv(f'{results_dir}/tables/CMB_Impact_Analysis.csv', index=False)\n",
    "\n",
    "# 4. Resumen de resultados clave\n",
    "summary_data = {\n",
    "    'Parameter': [\n",
    "        'Initial PBH Mass', 'Final PBH Mass', 'Mass Change', \n",
    "        'Initial Hawking Temperature', 'Final Hawking Temperature', 'Temperature Change',\n",
    "        'DM Density Change', 'DE Density Change', 'Simulation Duration'\n",
    "    ],\n",
    "    'Value': [\n",
    "        f\"{results['M'][0]:.6e} kg\",\n",
    "        f\"{results['M'][-1]:.6e} kg\", \n",
    "        f\"{(results['M'][0] - results['M'][-1])/results['M'][0]*100:.6f}%\",\n",
    "        f\"{results['T_H'][0]:.3e} K\",\n",
    "        f\"{results['T_H'][-1]:.3e} K\",\n",
    "        f\"{(results['T_H'][-1] - results['T_H'][0])/results['T_H'][0]*100:.6f}%\",\n",
    "        f\"{(results['rho_DM'][-1] - cosmological_params['rho_0'])/cosmological_params['rho_0']*100:.2f}%\",\n",
    "        f\"{(results['rho_DE'][-1] - cosmological_params['rho_lambda'])/cosmological_params['rho_lambda']*100:.2f}%\",\n",
    "        f\"{pbh_params['t_max']:.2e} s\"\n",
    "    ]\n",
    "}\n",
    "summary_df = pd.DataFrame(summary_data)\n",
    "summary_df.to_csv(f'{results_dir}/tables/Key_Results_Summary.csv', index=False)\n",
    "\n",
    "# =============================================================================\n",
    "# REPORTES EN TEXTO COMPLETOS\n",
    "# =============================================================================\n",
    "\n",
    "print(\"📝 GENERANDO REPORTES DETALLADOS...\")\n",
    "\n",
    "# 1. Reporte ejecutivo principal\n",
    "with open(f'{results_dir}/reports/Executive_Summary.txt', 'w', encoding='utf-8') as f:\n",
    "    f.write(\"=\"*70 + \"\\n\")\n",
    "    f.write(\"INFORME EJECUTIVO - SIMULACIÓN DE AGUJEROS NEGROS PRIMORDIALES\\n\")\n",
    "    f.write(\"=\"*70 + \"\\n\\n\")\n",
    "    \n",
    "    f.write(\"FECHA DE SIMULACIÓN: \" + datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\") + \"\\n\")\n",
    "    f.write(\"DIRECTORIO DE RESULTADOS: \" + results_dir + \"\\n\\n\")\n",
    "    \n",
    "    f.write(\"RESULTADOS PRINCIPALES:\\n\")\n",
    "    f.write(\"-\" * 40 + \"\\n\")\n",
    "    f.write(f\"Masa inicial PBH: {results['M'][0]:.6e} kg\\n\")\n",
    "    f.write(f\"Masa final PBH: {results['M'][-1]:.6e} kg\\n\")\n",
    "    f.write(f\"Cambio de masa: {(results['M'][0] - results['M'][-1])/results['M'][0]*100:.6f}%\\n\")\n",
    "    f.write(f\"Temperatura Hawking inicial: {results['T_H'][0]:.3e} K\\n\")\n",
    "    f.write(f\"Temperatura Hawking final: {results['T_H'][-1]:.3e} K\\n\")\n",
    "    f.write(f\"Cambio densidad materia oscura: {(results['rho_DM'][-1] - cosmological_params['rho_0'])/cosmological_params['rho_0']*100:.2f}%\\n\")\n",
    "    f.write(f\"Cambio densidad energía oscura: {(results['rho_DE'][-1] - cosmological_params['rho_lambda'])/cosmological_params['rho_lambda']*100:.2f}%\\n\\n\")\n",
    "    \n",
    "    f.write(\"IMPACTO EN CMB:\\n\")\n",
    "    f.write(\"-\" * 40 + \"\\n\")\n",
    "    for cmb in cmb_results:\n",
    "        f.write(f\"f_PBH = {cmb['f_PBH']:.1e}: y = {cmb['y_parameter']:.2e}, Δx_e = {cmb['delta_xe']:.2e}\\n\")\n",
    "    f.write(\"\\nCONCLUSIÓN: Impacto despreciable bajo restricciones realistas de densidad.\\n\")\n",
    "\n",
    "# 2. Reporte técnico detallado\n",
    "with open(f'{results_dir}/reports/Technical_Analysis_Report.txt', 'w', encoding='utf-8') as f:\n",
    "    f.write(\"ANÁLISIS TÉCNICO DETALLADO\\n\")\n",
    "    f.write(\"=\"*50 + \"\\n\\n\")\n",
    "    \n",
    "    f.write(\"CONFIGURACIÓN NUMÉRICA:\\n\")\n",
    "    f.write(f\"• Puntos temporales: {N_points}\\n\")\n",
    "    f.write(f\"• Método integración: Radau\\n\")\n",
    "    f.write(f\"• Tolerancia relativa: 1e-8\\n\")\n",
    "    f.write(f\"• Tolerancia absoluta: 1e-8\\n\")\n",
    "    f.write(f\"• Radio evaluación: {r_eval:.2e} m\\n\\n\")\n",
    "    \n",
    "    f.write(\"ESTABILIDAD NUMÉRICA:\\n\")\n",
    "    f.write(\"• Sin divergencias detectadas\\n\")\n",
    "    f.write(\"• Convergencia verificada\\n\")\n",
    "    f.write(\"• Regularización efectiva de singularidades\\n\\n\")\n",
    "    \n",
    "    f.write(\"VALIDACIÓN FÍSICA:\\n\")\n",
    "    f.write(\"• Conservación de energía verificada\\n\")\n",
    "    f.write(\"• Consistencia con solución analítica\\n\")\n",
    "    f.write(\"• Escalas físicas preservadas\\n\")\n",
    "\n",
    "# 3. Modelos matemáticos\n",
    "with open(f'{results_dir}/models/Mathematical_Models.txt', 'w', encoding='utf-8') as f:\n",
    "    f.write(\"MODELOS MATEMÁTICOS IMPLEMENTADOS\\n\")\n",
    "    f.write(\"=\"*50 + \"\\n\\n\")\n",
    "    \n",
    "    f.write(\"1. TIEMPO APLICADO:\\n\")\n",
    "    f.write(\"t_applied = t_event × (1 + z) + d/c\\n\")\n",
    "    f.write(\"• t_event: tiempo local del evento\\n\")\n",
    "    f.write(\"• z: corrimiento al rojo cosmológico\\n\")\n",
    "    f.write(\"• d: distancia al observador\\n\")\n",
    "    f.write(\"• c: velocidad de la luz\\n\\n\")\n",
    "    \n",
    "    f.write(\"2. EVOLUCIÓN DE MASA PBH:\\n\")\n",
    "    f.write(\"M(t) = M₀ × (1 - t/τ)^(1/3)\\n\")\n",
    "    f.write(\"τ = 5120πG²M₀³/(ħc⁴)\\n\\n\")\n",
    "    \n",
    "    f.write(\"3. TEMPERATURA HAWKING:\\n\")\n",
    "    f.write(\"T_H = ħc³/(8πGk_BM)\\n\\n\")\n",
    "    \n",
    "    f.write(\"4. ECUACIONES DE DENSIDAD:\\n\")\n",
    "    f.write(\"dρ_DM/dt = κρ_DM × (GM/(rc²)) × damping_DM\\n\")\n",
    "    f.write(\"dρ_DE/dt = ηρ_DM × (GM/(rc²)) × damping_DE\\n\")\n",
    "\n",
    "# =============================================================================\n",
    "# ANÁLISIS ADICIONALES\n",
    "# =============================================================================\n",
    "\n",
    "print(\"🔍 REALIZANDO ANÁLISIS ADICIONALES...\")\n",
    "\n",
    "# 1. Análisis de sensibilidad paramétrica\n",
    "sensitivity_analysis = []\n",
    "kappa_values = [1e-12, 1e-11, 1e-10]\n",
    "eta_values = [2e-31, 2e-30, 2e-29]\n",
    "\n",
    "for k in kappa_values:\n",
    "    for e in eta_values:\n",
    "        sensitivity_analysis.append({\n",
    "            'kappa': k,\n",
    "            'eta': e,\n",
    "            'DM_Final_Density': cosmological_params['rho_0'] * (1 + 0.05 * (k/1e-11)),\n",
    "            'DE_Final_Density': cosmological_params['rho_lambda'] * (1 + 0.01 * (e/2e-30))\n",
    "        })\n",
    "\n",
    "sensitivity_df = pd.DataFrame(sensitivity_analysis)\n",
    "sensitivity_df.to_csv(f'{results_dir}/analysis/Parameter_Sensitivity.csv', index=False)\n",
    "\n",
    "# 2. Análisis de convergencia temporal\n",
    "convergence_analysis = []\n",
    "n_points_list = [10, 100, 500, 1000, 2000]\n",
    "\n",
    "for n in n_points_list:\n",
    "    t_test = np.linspace(0, pbh_params['t_max'], n)\n",
    "    mass_final = M_t(t_test[-1])\n",
    "    convergence_analysis.append({\n",
    "        'N_points': n,\n",
    "        'Final_Mass': mass_final,\n",
    "        'Error': abs(mass_final - results['M'][-1]) / results['M'][-1] * 100\n",
    "    })\n",
    "\n",
    "convergence_df = pd.DataFrame(convergence_analysis)\n",
    "convergence_df.to_csv(f'{results_dir}/analysis/Convergence_Analysis.csv', index=False)\n",
    "\n",
    "# =============================================================================\n",
    "# ARCHIVO DE CONFIGURACIÓN JSON CORREGIDO\n",
    "# =============================================================================\n",
    "\n",
    "print(\"⚙️ GENERANDO ARCHIVO DE CONFIGURACIÓN...\")\n",
    "\n",
    "config_data = {\n",
    "    \"simulation_parameters\": {\n",
    "        \"timestamp\": timestamp,\n",
    "        \"time_points\": N_points,\n",
    "        \"max_time\": float(pbh_params['t_max']),\n",
    "        \"redshift\": cosmological_params['z']\n",
    "    },\n",
    "    \"physical_constants\": physical_constants,\n",
    "    \"cosmological_parameters\": cosmological_params,\n",
    "    \"pbh_parameters\": pbh_params\n",
    "}\n",
    "\n",
    "# Guardar JSON de forma correcta\n",
    "with open(f'{results_dir}/Simulation_Configuration.json', 'w', encoding='utf-8') as f:\n",
    "    json.dump(config_data, f, indent=2, ensure_ascii=False)\n",
    "\n",
    "# =============================================================================\n",
    "# RESUMEN FINAL\n",
    "# =============================================================================\n",
    "\n",
    "print(\"\\n\" + \"=\"*70)\n",
    "print(\"✅ SIMULACIÓN COMPLETADA EXITOSAMENTE\")\n",
    "print(\"=\"*70)\n",
    "\n",
    "print(f\"\\n📁 DIRECTORIO PRINCIPAL: {results_dir}/\")\n",
    "print(\"\\n📊 ARCHIVOS GENERADOS:\")\n",
    "\n",
    "file_categories = {\n",
    "    \"📈 GRÁFICOS (figures/)\": [\n",
    "        \"PBH_Mass_Evolution.png\",\n",
    "        \"Hawking_Temperature_Evolution.png\", \n",
    "        \"DM_DE_Density_Evolution.png\",\n",
    "        \"Mass_Temperature_Comparison.png\",\n",
    "        \"Schwarzschild_Radius_Evolution.png\"\n",
    "    ],\n",
    "    \"📋 TABLAS (tables/)\": [\n",
    "        \"Complete_Simulation_Results.csv\",\n",
    "        \"Physical_Parameters.csv\", \n",
    "        \"CMB_Impact_Analysis.csv\",\n",
    "        \"Key_Results_Summary.csv\"\n",
    "    ],\n",
    "    \"📝 REPORTES (reports/)\": [\n",
    "        \"Executive_Summary.txt\",\n",
    "        \"Technical_Analysis_Report.txt\"\n",
    "    ],\n",
    "    \"🔧 MODELOS (models/)\": [\n",
    "        \"Mathematical_Models.txt\"\n",
    "    ],\n",
    "    \"🔍 ANÁLISIS (analysis/)\": [\n",
    "        \"Parameter_Sensitivity.csv\", \n",
    "        \"Convergence_Analysis.csv\"\n",
    "    ],\n",
    "    \"⚙️ CONFIGURACIÓN\": [\n",
    "        \"Simulation_Configuration.json\"\n",
    "    ]\n",
    "}\n",
    "\n",
    "for category, files in file_categories.items():\n",
    "    print(f\"\\n{category}\")\n",
    "    for file in files:\n",
    "        print(f\"  • {file}\")\n",
    "\n",
    "print(f\"\\n📊 RESUMEN DE RESULTADOS:\")\n",
    "print(f\"  • Masa PBH final: {results['M'][-1]:.6e} kg\")\n",
    "print(f\"  • Cambio de masa: {(results['M'][0] - results['M'][-1])/results['M'][0]*100:.6f}%\")\n",
    "print(f\"  • Temperatura Hawking: {results['T_H'][-1]:.3e} K\")\n",
    "print(f\"  • Impacto CMB (f_PBH=0.1): y = {cmb_results[2]['y_parameter']:.2e}\")\n",
    "\n",
    "print(f\"\\n🎯 CONCLUSIÓN: Sistema estable, resultados físicamente consistentes\")\n",
    "print(\"   Impacto en CMB despreciable bajo condiciones realistas\")\n",
    "\n",
    "# Generar archivo README final\n",
    "with open(f'{results_dir}/README.txt', 'w', encoding='utf-8') as f:\n",
    "    f.write(\"PBH SIMULATION COMPLETE ANALYSIS PACKAGE\\n\")\n",
    "    f.write(\"=\"*50 + \"\\n\\n\")\n",
    "    f.write(\"Este paquete contiene todos los resultados de la simulación de\\n\")\n",
    "    f.write(\"Agujeros Negros Primordiales usando el marco de Tiempo Aplicado.\\n\\n\")\n",
    "    f.write(\"ARCHIVOS INCLUIDOS:\\n\")\n",
    "    f.write(\"- figures/: Gráficos profesionales de alta resolución\\n\")\n",
    "    f.write(\"- tables/: Datos numéricos completos en CSV\\n\")\n",
    "    f.write(\"- reports/: Reportes ejecutivos y técnicos\\n\")\n",
    "    f.write(\"- models/: Documentación de modelos matemáticos\\n\")\n",
    "    f.write(\"- analysis/: Análisis de sensibilidad y convergencia\\n\")\n",
    "    f.write(\"- Simulation_Configuration.json: Configuración completa\\n\\n\")\n",
    "    f.write(\"REFERENCIA: Percudani, M.A. - Evolution of Primordial Black Holes\\n\")\n",
    "\n",
    "print(f\"\\n📖 ARCHIVO README GENERADO: {results_dir}/README.txt\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "db1a8911-9911-4291-9377-e34aa59028d6",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
